In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('/content/heart.csv')

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

# Data Cleaning

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
df.duplicated().sum()

723

In [ ]:
df_unique = df.drop_duplicates()

# Data integration

In [ ]:
# merged_df = pd.merge(air_quality_df, heart_disease_df, on='age', how='inner')

# Data transformation

In [ ]:
df['trestbps'] = df['trestbps'].apply(lambda x: 1 if x > 130 else 0)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,0,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,0,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,0,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,0,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,0,294,1,1,106,0,1.9,1,3,2,0

# Data model Building

In [ ]:
dataset = df.fillna(1000)
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,0,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,0,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,0,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,0,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,0,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,0,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,0,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,0,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,0,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,0,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
from sklearn.model_selection import train_test_split
x=dataset.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12]].values
x
y=dataset.iloc[:,-1].values
y
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=l1.predict(X_test)
print(y_pred)

[ 9.32747647e-01  1.27027917e+00  7.95946923e-02  9.28141871e-01
  1.73458228e-01  5.97794577e-01 -8.44888750e-02 -1.54243013e-01
  7.49217769e-01  1.37802278e-02  9.42495798e-01 -1.78863257e-01
  7.71044035e-01  8.02049093e-01  2.47404018e-01  8.45962098e-01
 -1.08442613e-01  9.70566745e-01  7.69315284e-01 -5.59370682e-02
  7.10332233e-01  1.73806155e-01  5.02264492e-01 -1.50830488e-01
  7.10332233e-01  6.69564530e-01  1.01465476e+00  5.94774534e-01
 -1.48805413e-01  7.99905172e-01  6.28249761e-01  7.62233047e-01
  4.56835118e-01  1.27027917e+00  7.77472809e-01  6.67306979e-01
  7.10332233e-01  4.52107209e-01  6.61160155e-01  8.68638331e-01
 -1.54243013e-01  2.05399967e-01  5.22271156e-01  5.02264492e-01
  3.55051275e-01 -2.95877460e-01  2.52776871e-01  4.48790046e-01
  6.50741019e-01  5.42890564e-01  6.14748354e-01 -2.04952471e-01
  7.05922945e-01  9.91718426e-04  1.01465476e+00  6.61160155e-01
  3.57573584e-01 -9.89448959e-02  8.17745094e-01  9.12657021e-01
  5.51158380e-01  1.51148984e-01 -1.48805413e-01  5.42890564e-01
 -1.82563330e-01  3.64869331e-01  1.23255194e+00  6.01668413e-01
 -2.95877460e-01  1.10634495e+00  6.08169947e-01 -1.48805413e-01
  4.99811748e-01  7.98895082e-01  6.54406439e-01  5.77466852e-01
 -8.44888750e-02  8.62457770e-01  5.65579457e-01  7.71286386e-01
  3.47201977e-01  4.16576855e-01  2.40946772e-01 -1.24217855e-01
  7.11477267e-01 -2.06080053e-01  9.42495798e-01  3.18581098e-01
  3.47201977e-01  7.99905172e-01  5.20203289e-01 -5.59370682e-02
  7.69825235e-01  8.84681901e-01  6.90248425e-01  6.26284424e-01
  6.01668413e-01  3.29386971e-01 -2.07918210e-01  7.99484289e-02
  3.94129191e-01  1.36487359e-01  6.78118991e-01  6.82065040e-01
  2.05547074e-01  7.72794813e-01 -9.89448959e-02  7.16000905e-01
  4.19957058e-01  1.00819789e+00  8.17745094e-01  1.00819789e+00
  1.07182244e+00  1.90454479e-01  7.86722997e-01  1.06171587e+00
  7.07299758e-01  8.07472455e-01  9.17201125e-01 -7.56527702e-02
  5.16658263e-01  6.09299131e-01 -1.44319285e-01  2.63641859e-01
  2.25977333e-01 -1.50830488e-01  6.92877260e-01  5.87761569e-01
  6.08169947e-01  8.26416384e-01  7.62233047e-01 -2.07918210e-01
  1.09010577e+00  3.94129191e-01 -2.77722897e-02  9.29095694e-01
  3.00766573e-01  6.09299131e-01  9.29095694e-01  7.07299758e-01
  5.24087693e-01  8.61335793e-01  9.65105170e-01  5.75984912e-02
  6.16279380e-01  6.33489518e-01  6.14748354e-01  9.03802217e-01
  5.58016733e-01  1.48794303e-01  4.56835118e-01 -2.95877460e-01
  5.86811108e-01  5.24087693e-01  3.35797344e-01  2.05804206e-01
  6.65583066e-01  8.26416384e-01  2.66757097e-01  2.05399967e-01
  5.22271156e-01  9.74786291e-01  1.36487359e-01  1.36487359e-01
  2.37542540e-01  2.85300691e-01  2.95797950e-01  1.46946347e-01
  2.73483877e-01  9.03802217e-01  4.99811748e-01  5.94854375e-01
  8.68934901e-01 -1.87998438e-01  8.94669644e-01  1.27027917e+00
  9.64784554e-01 -4.21933939e-01  6.78118991e-01  9.26095613e-01
  9.64653696e-01 -1.11388106e-01  7.50216281e-01  7.05922945e-01
  6.43953124e-01  9.17201125e-01  7.77472809e-01  8.17745094e-01
  6.45549543e-01  9.81222876e-01  1.01177158e+00  5.65579457e-01
  6.82219164e-01  7.05922945e-01 -9.89448959e-02  2.31799125e-01
  9.00397816e-01 -7.66760331e-02  8.93928010e-01  9.69713301e-01
  5.28245916e-01  8.34183619e-01  9.69713301e-01  1.34900697e-01
  3.92796855e-01  5.50519004e-01  6.71612195e-01  1.08579959e+00
  4.36480458e-01  6.09299131e-01  8.34183619e-01  2.19900669e-01
  1.12179979e+00  5.20203289e-01  2.05804206e-01  2.82386638e-01
  6.36663796e-01  2.95797950e-01  5.70790624e-01 -2.77722897e-02
  6.88733213e-01  2.40946772e-01  7.99484289e-02  9.07414070e-01
  7.42931784e-01  6.86168983e-01  8.07472455e-01  7.15476920e-01
 -1.78863257e-01  5.16658263e-01  6.82219164e-01  3.92344475e-01
  7.02373491e-01  6.65583066e-01  1.48794303e-01 -8.44888750e-02
  3.41139650e-01  3.47967739e-01  9.27132703e-01  6.00776491e-01
  4.57532899e-01  6.71326666e-01  1.19983253e+00  1.79523956e-01
 -1.12986942e-01  7.16000905e-01  2.92896002e-01  3.94129191e-01
  7.03725036e-01  1.31732194e-01  7.98895082e-01  1.37802278e-02
  4.32839414e-01 -4.21933939e-01  2.63641859e-01  9.64095221e-01
  1.11010474e-01  4.97686672e-01 -6.58144118e-02  7.29665706e-01
  6.90018604e-02  4.52107209e-01  8.40699989e-01  1.45518924e-01
  3.57573584e-01 -1.31077004e-01 -9.04207925e-02  1.19235614e+00
  2.82386638e-01  5.24378995e-01  1.11010474e-01  6.14748354e-01
  4.92656488e-01  8.68934901e-01  8.58783658e-02  7.76430398e-01
  9.17907567e-01  5.85265831e-01  5.87761569e-01  9.67838544e-01
 -2.16281055e-01  8.01832394e-01  3.59341625e-01  2.82386638e-01
  9.17907567e-01 -2.16281055e-01  9.83340452e-01  7.15476920e-01
  3.38192624e-01  6.54406439e-01  6.16279380e-01  4.19957058e-01
  9.64784554e-01  9.17201125e-01  1.48794303e-01  7.19905833e-01
  9.17907567e-01 -1.44319285e-01  4.48790046e-01  9.52243021e-01
  5.50519004e-01  9.03755657e-02  9.55351495e-01  9.64784554e-01
  5.58016733e-01  6.90018604e-02  3.96132096e-02  8.06365785e-01]

In [ ]:
print("Training Accuracy",l1.score(X_train,y_train))

Training Accuracy 0.5295926037528187

In [ ]:
print("Testing Accuracy",l1.score(X_test,y_pred))

Testing Accuracy 1.0

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred)*100)

44.61540884167763